language: generic

sudo: required
services: 
    - docker

before_install:
    - docker build -t chhamilton/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true chhamilton/docker-react npm run test

    #- docker run chhamilton/docker-react npm run test -- --coverage


